PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE quotes(
id INTEGER PRIMARY KEY AUTOINCREMENT,
quote TEXT NOT NULL);
INSERT INTO quotes VALUES(1,'The best way to get started is to quit talking and begin doing.');
INSERT INTO quotes VALUES(2,'Don''t let yesterday take up too much of today.');
INSERT INTO quotes VALUES(3,'It''s not whether you get knocked down, it''s whether you get up.');
INSERT INTO quotes VALUES(4,'If you are working on something exciting, it will keep you motivated.');
INSERT INTO quotes VALUES(5,'Success is walking from failure to failure with no loss of enthusiasm.');
INSERT INTO quotes VALUES(6,'Hard work beats talent when talent doesn’t work hard.');
INSERT INTO quotes VALUES(7,'Dream big and dare to fail.');
INSERT INTO quotes VALUES(8,'Do what you can with all you have, wherever you are.');
INSERT INTO quotes VALUES(9,'You are never too old to set another goal or to dream a new dream.');
INSERT INTO quotes VALUES(10,'What you get by achieving your goals is not as important as what you become by achieving your goals.');
INSERT INTO quotes VALUES(11,'Life is 10% what happens to us and 90% how we react to it.');
INSERT INTO quotes VALUES(12,'An unexamined life is not worth living.');
INSERT INTO quotes VALUES(13,'Your time is limited, so don’t waste it living someone else’s life.');
INSERT INTO quotes VALUES(14,'I attribute my success to this: I never gave or took any excuse.');
INSERT INTO quotes VALUES(15,'The mind is everything. What you think you become.');
INSERT INTO quotes VALUES(16,'The best revenge is massive success.');
INSERT INTO quotes VALUES(17,'The only limit to our realization of tomorrow is our doubts of today.');
INSERT INTO quotes VALUES(18,'Creativity is intelligence having fun.');
INSERT INTO quotes VALUES(19,'Do not wait to strike till the iron is hot; but make it hot by striking.');
INSERT INTO quotes VALUES(20,'Great minds discuss ideas; average minds discuss events; small minds discuss people.');
INSERT INTO quotes VALUES(21,'Believe you can and you''re halfway there.');
INSERT INTO quotes VALUES(22,'Act as if what you do makes a difference. It does.');
INSERT INTO quotes VALUES(23,'What we achieve inwardly will change outer reality.');
INSERT INTO quotes VALUES(24,'You don’t have to be great to start, but you have to start to be great.');
INSERT INTO quotes VALUES(25,'Keep your eyes on the stars and your feet on the ground.');
INSERT INTO quotes VALUES(26,'Success usually comes to those who are too busy to be looking for it.');
INSERT INTO quotes VALUES(27,'The harder you work for something, the greater you’ll feel when you achieve it.');
INSERT INTO quotes VALUES(28,'Don’t watch the clock; do what it does. Keep going.');
INSERT INTO quotes VALUES(29,'Push yourself, because no one else is going to do it for you.');
INSERT INTO quotes VALUES(30,'Failure is not the opposite of success; it’s part of success.');
INSERT INTO quotes VALUES(31,'It always seems impossible until it’s done.');
INSERT INTO quotes VALUES(32,'Opportunities don’t happen, you create them.');
INSERT INTO quotes VALUES(33,'Sometimes we’re tested not to show our weaknesses, but to discover our strengths.');
INSERT INTO quotes VALUES(34,'The secret of getting ahead is getting started.');
INSERT INTO quotes VALUES(35,'Don’t wait. The time will never be just right.');
INSERT INTO quotes VALUES(36,'Do something today that your future self will thank you for.');
INSERT INTO quotes VALUES(37,'Little things make big days.');
INSERT INTO quotes VALUES(38,'It’s going to be hard, but hard does not mean impossible.');
INSERT INTO quotes VALUES(39,'Don’t limit your challenges. Challenge your limits.');
INSERT INTO quotes VALUES(40,'Great things never come from comfort zones.');
INSERT INTO quotes VALUES(41,'Dream it. Wish it. Do it.');
INSERT INTO quotes VALUES(42,'Stay positive, work hard, make it happen.');
INSERT INTO quotes VALUES(43,'Work until your idols become rivals.');
INSERT INTO quotes VALUES(44,'Don’t stop when you’re tired. Stop when you’re done.');
INSERT INTO quotes VALUES(45,'The key to success is to focus on goals, not obstacles.');
INSERT INTO quotes VALUES(46,'Success is not in what you have, but who you are.');
INSERT INTO quotes VALUES(47,'The way to get started is to quit talking and begin doing.');
INSERT INTO quotes VALUES(48,'Motivation is what gets you started. Habit is what keeps you going.');
INSERT INTO quotes VALUES(49,'If you can dream it, you can do it.');
INSERT INTO quotes VALUES(50,'Strive not to be a success, but rather to be of value.');
INSERT INTO quotes VALUES(51,'Do one thing every day that scares you.');
INSERT INTO quotes VALUES(52,'The journey of a thousand miles begins with one step.');
INSERT INTO quotes VALUES(53,'You miss 100% of the shots you don’t take.');
INSERT INTO quotes VALUES(54,'Everything you’ve ever wanted is on the other side of fear.');
INSERT INTO quotes VALUES(55,'Opportunities multiply as they are seized.');
INSERT INTO quotes VALUES(56,'Don’t count the days, make the days count.');
INSERT INTO quotes VALUES(57,'Your limitation—it’s only your imagination.');
INSERT INTO quotes VALUES(58,'Push yourself because no one else is going to do it for you.');
INSERT INTO quotes VALUES(59,'Sometimes later becomes never. Do it now.');
INSERT INTO quotes VALUES(60,'Great things never came from comfort zones.');
INSERT INTO quotes VALUES(61,'Dream bigger. Do bigger.');
INSERT INTO quotes VALUES(62,'Don’t stop until you’re proud.');
INSERT INTO quotes VALUES(63,'Little by little, a little becomes a lot.');
INSERT INTO quotes VALUES(64,'It’s not about perfect. It’s about effort.');
INSERT INTO quotes VALUES(65,'Success is the sum of small efforts repeated day in and day out.');
INSERT INTO quotes VALUES(66,'Work hard in silence, let success make the noise.');
INSERT INTO quotes VALUES(67,'Don’t wait for opportunity. Create it.');
INSERT INTO quotes VALUES(68,'Failure is the condiment that gives success its flavor.');
INSERT INTO quotes VALUES(69,'The expert in anything was once a beginner.');
INSERT INTO quotes VALUES(70,'Believe in yourself and all that you are.');
INSERT INTO quotes VALUES(71,'Stay patient and trust your journey.');
INSERT INTO quotes VALUES(72,'Do what you love and success will follow.');
INSERT INTO quotes VALUES(73,'Focus on being productive instead of busy.');
INSERT INTO quotes VALUES(74,'Don’t quit. Suffer now and live the rest of your life as a champion.');
INSERT INTO quotes VALUES(75,'Your future is created by what you do today, not tomorrow.');
INSERT INTO quotes VALUES(76,'Success is not final, failure is not fatal: it is the courage to continue that counts.');
INSERT INTO quotes VALUES(77,'Small daily improvements over time lead to stunning results.');
INSERT INTO quotes VALUES(78,'The best time to plant a tree was 20 years ago. The second best time is now.');
INSERT INTO quotes VALUES(79,'Energy and persistence conquer all things.');
INSERT INTO quotes VALUES(80,'A goal without a plan is just a wish.');
INSERT INTO quotes VALUES(81,'It’s never too late to be what you might have been.');
INSERT INTO quotes VALUES(82,'Hustle until your haters ask if you’re hiring.');
INSERT INTO quotes VALUES(83,'Success doesn’t come to you; you go to it.');
INSERT INTO quotes VALUES(84,'Do what is right, not what is easy.');
INSERT INTO quotes VALUES(85,'Little progress each day adds up to big results.');
INSERT INTO quotes VALUES(86,'Be so good they can’t ignore you.');
INSERT INTO quotes VALUES(87,'Don’t be afraid to give up the good to go for the great.');
INSERT INTO quotes VALUES(88,'The harder the conflict, the more glorious the triumph.');
INSERT INTO quotes VALUES(89,'Fall seven times and stand up eight.');
INSERT INTO quotes VALUES(90,'Success is liking yourself, liking what you do, and liking how you do it.');
INSERT INTO quotes VALUES(91,'If opportunity doesn’t knock, build a door.');
INSERT INTO quotes VALUES(92,'The purpose of life is a life of purpose.');
INSERT INTO quotes VALUES(93,'Don’t wait for the perfect moment. Take the moment and make it perfect.');
INSERT INTO quotes VALUES(94,'Doubt kills more dreams than failure ever will.');
INSERT INTO quotes VALUES(95,'Do not stop thinking of life as an adventure.');
INSERT INTO quotes VALUES(96,'Great minds have purposes; others have wishes.');
INSERT INTO quotes VALUES(97,'The distance between insanity and genius is measured only by success.');
INSERT INTO quotes VALUES(98,'If you want to lift yourself up, lift up someone else.');
INSERT INTO quotes VALUES(99,'Start where you are. Use what you have. Do what you can.');
INSERT INTO quotes VALUES(100,'Be fearless in the pursuit of what sets your soul on fire.');
CREATE TABLE tasks(
id INTEGER PRIMARY KEY AUTOINCREMENT,
description TEXT NOT NULL,
max_time INTEGER NOT NULL);
INSERT INTO tasks VALUES(1,'Turn off unused lights and electronics for an hour',5);
INSERT INTO tasks VALUES(2,'Collect and recycle 5 plastic bottles',3);
INSERT INTO tasks VALUES(3,'Walk or bike instead of driving for a short trip',15);
INSERT INTO tasks VALUES(4,'Participate in a community cleanup or pick up litter nearby',20);
INSERT INTO tasks VALUES(5,'Compost kitchen scraps in a small bin',15);
INSERT INTO tasks VALUES(6,'Use reusable bags for shopping today',1);
INSERT INTO tasks VALUES(7,'Take a short nature walk and note what you see',15);
INSERT INTO tasks VALUES(8,'Collect rainwater for reuse in household tasks',15);
INSERT INTO tasks VALUES(9,'Switch one household cleaning product to an eco-friendly version',5);
INSERT INTO tasks VALUES(10,'Donate old clothes or items instead of throwing away',15);
INSERT INTO tasks VALUES(11,'Pick up litter along a short walking route',10);
INSERT INTO tasks VALUES(12,'Replace one incandescent bulb with LED',5);
INSERT INTO tasks VALUES(13,'Unplug chargers when not in use',2);
INSERT INTO tasks VALUES(14,'Write a social media post encouraging sustainable habits',10);
INSERT INTO tasks VALUES(15,'Learn about a local endangered species online',15);
INSERT INTO tasks VALUES(16,'Reduce water usage by a few liters today',1);
INSERT INTO tasks VALUES(17,'Research eco-friendly alternatives to daily products',30);
INSERT INTO tasks VALUES(18,'Repair or upcycle an old item instead of discarding it',40);
INSERT INTO tasks VALUES(19,'Write a short plan to reduce household energy use this week',20);
INSERT INTO tasks VALUES(20,'Switch off water taps when not in use for the day',1);
INSERT INTO tasks VALUES(21,'Collect and separate recyclables from trash',10);
INSERT INTO tasks VALUES(22,'Share tips about reducing carbon footprint with friends/family',5);
INSERT INTO tasks VALUES(23,'Reduce single-use plastics for one day',5);
INSERT INTO tasks VALUES(24,'Take a shorter shower today',3);
INSERT INTO tasks VALUES(25,'Use a reusable water bottle for the day',1);
INSERT INTO tasks VALUES(26,'Pick up microplastics or trash from streets or sidewalks',10);
INSERT INTO tasks VALUES(27,'Check for energy-wasting devices and unplug them',5);
INSERT INTO tasks VALUES(28,'Document and share local wildlife sightings online',15);
INSERT INTO tasks VALUES(29,'Organize old papers, books, or electronics for donation or recycling',20);
INSERT INTO tasks VALUES(30,'Plan one meal to reduce food waste',10);
INSERT INTO tasks VALUES(31,'Write a list of 5 ways to save energy at home',5);
INSERT INTO tasks VALUES(32,'Replace disposable straws with reusable ones',1);
INSERT INTO tasks VALUES(33,'Clean up small trash in public areas during a walk',10);
INSERT INTO tasks VALUES(34,'Learn about renewable energy options in your area',20);
INSERT INTO tasks VALUES(35,'Make DIY natural cleaning supplies',30);
INSERT INTO tasks VALUES(36,'Check for water leaks and fix them if possible',5);
INSERT INTO tasks VALUES(37,'Reuse jars or containers instead of buying new ones',3);
INSERT INTO tasks VALUES(38,'Participate in an online environmental awareness campaign',15);
INSERT INTO tasks VALUES(39,'Turn off devices in standby mode for a day',2);
INSERT INTO tasks VALUES(40,'Recycle old batteries properly',5);
INSERT INTO tasks VALUES(41,'Write to a local representative about environmental issues',20);
INSERT INTO tasks VALUES(42,'Donate seeds to community or school gardens',10);
INSERT INTO tasks VALUES(43,'Collect and recycle aluminum cans',5);
INSERT INTO tasks VALUES(44,'Pick up trash on a short street walk',5);
INSERT INTO tasks VALUES(45,'Plan to reduce meat consumption for one meal',5);
INSERT INTO tasks VALUES(46,'Use a broom instead of a hose to clean outdoor areas',5);
INSERT INTO tasks VALUES(47,'Replace one paper towel roll with reusable cloths',5);
INSERT INTO tasks VALUES(48,'Create small seed bombs to scatter in nearby green areas',10);
INSERT INTO tasks VALUES(49,'Pick up fallen litter in a local park or green area',8);
INSERT INTO tasks VALUES(50,'Use public transport for a short trip instead of driving',10);
INSERT INTO tasks VALUES(51,'Switch off lights in unused rooms for a day',1);
INSERT INTO tasks VALUES(52,'Repair clothes instead of throwing them away',15);
INSERT INTO tasks VALUES(53,'Collect leaves or small yard debris for compost',5);
INSERT INTO tasks VALUES(54,'Reflect on 3 ways you helped the environment today',5);
INSERT INTO tasks VALUES(55,'Clean small debris in shared outdoor spaces',10);
INSERT INTO tasks VALUES(56,'Make a small DIY compost bin using kitchen scraps',15);
INSERT INTO tasks VALUES(57,'Reduce paper usage by going digital for one task',5);
INSERT INTO tasks VALUES(58,'Pick up 10 pieces of trash near your home or workplace',3);
INSERT INTO tasks VALUES(59,'Learn about the carbon footprint of common household items',10);
INSERT INTO tasks VALUES(60,'Turn off the tap while brushing teeth for the day',1);
INSERT INTO tasks VALUES(61,'Plan one zero-waste activity for the week',15);
INSERT INTO tasks VALUES(62,'Check local recycling rules and organize your trash accordingly',10);
INSERT INTO tasks VALUES(63,'Swap single-use items with reusable alternatives',5);
INSERT INTO tasks VALUES(64,'Educate someone about sustainable living',5);
INSERT INTO tasks VALUES(65,'Collect recyclable packaging materials for proper disposal',10);
INSERT INTO tasks VALUES(66,'Share an eco-friendly tip on social media',5);
INSERT INTO tasks VALUES(67,'Check energy usage on home devices and adjust settings',10);
INSERT INTO tasks VALUES(68,'Use leftover food for composting or creative recipes',5);
INSERT INTO tasks VALUES(69,'Pick up trash on a nearby walking or jogging path',5);
INSERT INTO tasks VALUES(70,'Research one sustainable habit to adopt this week',5);
INSERT INTO tasks VALUES(71,'Participate in a virtual tree planting or donation program',60);
INSERT INTO tasks VALUES(72,'Make a list of 3 ways to reduce household waste',5);
INSERT INTO tasks VALUES(73,'Turn off non-essential devices for a few hours',3);
INSERT INTO tasks VALUES(74,'Plan a day without single-use plastics',15);
INSERT INTO tasks VALUES(75,'Sort recyclable items from trash at home',5);
INSERT INTO tasks VALUES(76,'Pick up litter in your neighborhood during a short walk',5);
INSERT INTO tasks VALUES(77,'Replace one plastic item with a sustainable alternative',2);
INSERT INTO tasks VALUES(78,'Learn about local environmental policies online',10);
INSERT INTO tasks VALUES(79,'Reflect on 3 ways to reduce energy consumption at home',5);
INSERT INTO tasks VALUES(80,'Use a reusable coffee cup or mug for the day',1);
INSERT INTO tasks VALUES(81,'Check your home for drafts and suggest improvements',10);
INSERT INTO tasks VALUES(82,'Write down 5 eco-friendly actions you’ll do tomorrow',5);
INSERT INTO tasks VALUES(83,'Pick up litter in a small park area',5);
INSERT INTO tasks VALUES(84,'Replace disposable cutlery with reusable options',2);
INSERT INTO tasks VALUES(85,'Make a small eco-awareness poster or note',15);
INSERT INTO tasks VALUES(86,'Participate in a community recycling initiative',60);
INSERT INTO tasks VALUES(87,'Educate yourself about climate-friendly diets',10);
INSERT INTO tasks VALUES(88,'Turn off water heater for a few hours',5);
INSERT INTO tasks VALUES(89,'Pick up small trash along a bus stop or local area',3);
INSERT INTO tasks VALUES(90,'Research one local endangered species and share facts',10);
INSERT INTO tasks VALUES(91,'Reflect on your weekly carbon footprint and note one improvement',10);
INSERT INTO tasks VALUES(92,'Organize a mini swap for household items with friends',20);
INSERT INTO tasks VALUES(93,'Donate old electronic devices for recycling',15);
INSERT INTO tasks VALUES(94,'Write a short plan to reduce plastic usage this week',10);
INSERT INTO tasks VALUES(95,'Participate in a short online workshop about sustainability',60);
INSERT INTO tasks VALUES(96,'Collect and recycle small metal items',5);
INSERT INTO tasks VALUES(97,'Share one positive environmental action you did today with a friend',2);
INSERT INTO tasks VALUES(98,'Turn off extra lights for the day',1);
INSERT INTO tasks VALUES(99,'Plan a week of energy-saving actions at home',15);
INSERT INTO tasks VALUES(100,'Pick up litter during a short commute walk',5);
INSERT INTO tasks VALUES(101,'Use public transport instead of car for one trip',10);
INSERT INTO tasks VALUES(102,'Learn a new tip to reduce food waste at home',5);
INSERT INTO tasks VALUES(103,'Turn off extra appliances when not in use',2);
INSERT INTO tasks VALUES(104,'Pick up 10 pieces of litter in your neighborhood',5);
INSERT INTO tasks VALUES(105,'Use a reusable shopping bag for all purchases today',1);
INSERT INTO tasks VALUES(106,'Sort recyclables from trash at home',5);
INSERT INTO tasks VALUES(107,'Take a short walk and collect small trash along the way',10);
INSERT INTO tasks VALUES(108,'Switch one disposable item with a sustainable alternative',2);
INSERT INTO tasks VALUES(109,'Educate a friend about reducing plastic use',5);
INSERT INTO tasks VALUES(110,'Use public transport or walk for one short trip',10);
INSERT INTO tasks VALUES(111,'Reflect on 3 ways to save energy today',5);
INSERT INTO tasks VALUES(112,'Compost leftover vegetable scraps in a small container',10);
INSERT INTO tasks VALUES(113,'Replace one paper towel roll with reusable cloths',5);
INSERT INTO tasks VALUES(114,'Pick up litter near a bus stop or street corner',3);
INSERT INTO tasks VALUES(115,'Write a short note to encourage sustainable habits',5);
INSERT INTO tasks VALUES(116,'Donate old clothes or items to charity instead of trashing',15);
INSERT INTO tasks VALUES(117,'Switch off lights in unused rooms for the day',1);
INSERT INTO tasks VALUES(118,'Replace disposable coffee cup with a reusable mug',1);
INSERT INTO tasks VALUES(119,'Collect and recycle metal cans',5);
INSERT INTO tasks VALUES(120,'Document local wildlife sightings',10);
INSERT INTO tasks VALUES(121,'Use leftover food creatively to avoid waste',5);
INSERT INTO tasks VALUES(122,'Learn a tip to reduce water usage at home',5);
INSERT INTO tasks VALUES(123,'Participate in an online eco-awareness event',60);
INSERT INTO tasks VALUES(124,'Research local recycling rules',10);
INSERT INTO tasks VALUES(125,'Replace one plastic straw with a reusable straw',1);
INSERT INTO tasks VALUES(126,'Pick up trash during a short park visit',10);
INSERT INTO tasks VALUES(127,'Reflect on one eco-friendly change you can make tomorrow',5);
INSERT INTO tasks VALUES(128,'Turn off standby devices for a few hours',2);
INSERT INTO tasks VALUES(129,'Share an eco-tip on social media',5);
INSERT INTO tasks VALUES(130,'Collect small yard debris for compost',5);
INSERT INTO tasks VALUES(131,'Learn about carbon footprint of common products',10);
INSERT INTO tasks VALUES(132,'Make a small DIY compost container for scraps',15);
INSERT INTO tasks VALUES(133,'Use a broom instead of hose to clean outdoor areas',5);
INSERT INTO tasks VALUES(134,'Plan a week to reduce single-use plastics',10);
INSERT INTO tasks VALUES(135,'Participate in a virtual environmental workshop',60);
INSERT INTO tasks VALUES(136,'Pick up microplastics or trash from sidewalks',10);
INSERT INTO tasks VALUES(137,'Repair or upcycle an old item instead of discarding',20);
INSERT INTO tasks VALUES(138,'Turn off water heater for a few hours',5);
INSERT INTO tasks VALUES(139,'Check home devices for energy efficiency settings',10);
INSERT INTO tasks VALUES(140,'Reflect on one sustainable habit to adopt this week',5);
INSERT INTO tasks VALUES(141,'Donate old electronic items for recycling',15);
INSERT INTO tasks VALUES(142,'Learn one new sustainable cooking tip',5);
INSERT INTO tasks VALUES(143,'Organize recyclable packaging materials',5);
INSERT INTO tasks VALUES(144,'Make a list of ways to reduce household energy usage',10);
INSERT INTO tasks VALUES(145,'Participate in an online tree planting program',60);
INSERT INTO tasks VALUES(146,'Turn off extra lights in rooms not in use',1);
INSERT INTO tasks VALUES(147,'Pick up litter along a walking or jogging path',5);
INSERT INTO tasks VALUES(148,'Use reusable containers for leftovers instead of plastic wrap',2);
INSERT INTO tasks VALUES(149,'Plan one meat-free meal to reduce carbon footprint',5);
INSERT INTO tasks VALUES(150,'Educate a family member about water conservation',5);
INSERT INTO tasks VALUES(151,'Write a short environmental awareness post',10);
INSERT INTO tasks VALUES(152,'Sort electronic waste for proper recycling',15);
INSERT INTO tasks VALUES(153,'Collect and recycle plastic caps or small items',5);
INSERT INTO tasks VALUES(154,'Reflect on eco-friendly habits you maintained this week',5);
INSERT INTO tasks VALUES(155,'Use energy-saving settings on computer or devices',5);
INSERT INTO tasks VALUES(156,'Turn off devices at night to save electricity',5);
INSERT INTO tasks VALUES(157,'Research one local environmental initiative',10);
INSERT INTO tasks VALUES(158,'Pick up trash from a 50-meter street stretch',3);
INSERT INTO tasks VALUES(159,'Switch disposable cutlery with reusable alternatives',2);
INSERT INTO tasks VALUES(160,'Document your sustainable actions for the week',10);
INSERT INTO tasks VALUES(161,'Plan to reduce paper usage for the day',5);
INSERT INTO tasks VALUES(162,'Clean a small area of shared outdoor space',10);
INSERT INTO tasks VALUES(163,'Write down 5 ways to reduce personal carbon footprint',5);
INSERT INTO tasks VALUES(164,'Replace plastic wrap with reusable alternatives',5);
INSERT INTO tasks VALUES(165,'Participate in local recycling collection program',60);
INSERT INTO tasks VALUES(166,'Reflect on your water usage and ways to save',5);
INSERT INTO tasks VALUES(167,'Share a positive environmental action with a friend',2);
INSERT INTO tasks VALUES(168,'Pick up litter in nearby green spaces',8);
INSERT INTO tasks VALUES(169,'Repair clothes instead of discarding',15);
INSERT INTO tasks VALUES(170,'Reflect on 3 ways to reduce waste today',5);
INSERT INTO tasks VALUES(171,'Use public transport instead of car for one short trip',10);
INSERT INTO tasks VALUES(172,'Research energy-efficient alternatives to common devices',10);
INSERT INTO tasks VALUES(173,'Switch one household cleaning product to eco-friendly',5);
INSERT INTO tasks VALUES(174,'Take a short walk and photograph interesting plants or wildlife',10);
INSERT INTO tasks VALUES(175,'Collect leftover paper for recycling',3);
INSERT INTO tasks VALUES(176,'Organize and donate old books',10);
INSERT INTO tasks VALUES(177,'Reflect on how to reduce plastic usage this week',5);
INSERT INTO tasks VALUES(178,'Turn off non-essential devices for the day',3);
INSERT INTO tasks VALUES(179,'Educate a friend about recycling rules',5);
INSERT INTO tasks VALUES(180,'Pick up trash near playgrounds or schools',5);
INSERT INTO tasks VALUES(181,'Write a short plan to reduce food waste at home',10);
INSERT INTO tasks VALUES(182,'Use reusable shopping bags for a week',1);
INSERT INTO tasks VALUES(183,'Make a small DIY seed bomb',15);
INSERT INTO tasks VALUES(184,'Pick up litter on a nearby trail or path',10);
INSERT INTO tasks VALUES(185,'Research low-carbon travel alternatives',10);
INSERT INTO tasks VALUES(186,'Reflect on your household’s energy usage',5);
INSERT INTO tasks VALUES(187,'Participate in an online eco-challenge',60);
INSERT INTO tasks VALUES(188,'Collect small trash items in public areas',5);
INSERT INTO tasks VALUES(189,'Plan a day without single-use plastics',15);
INSERT INTO tasks VALUES(190,'Replace disposable plates with reusable ones',2);
INSERT INTO tasks VALUES(191,'Share eco-friendly tips with neighbors',5);
INSERT INTO tasks VALUES(192,'Switch to energy-efficient bulbs in one room',5);
INSERT INTO tasks VALUES(193,'Pick up small litter on a street corner',3);
INSERT INTO tasks VALUES(194,'Document eco-friendly actions for the week',5);
INSERT INTO tasks VALUES(195,'Reflect on one change to reduce water usage',5);
INSERT INTO tasks VALUES(196,'Repair small household items instead of discarding',10);
INSERT INTO tasks VALUES(197,'Pick up microplastics from park benches or sidewalks',8);
INSERT INTO tasks VALUES(198,'Write a note encouraging sustainability to a friend or family member',5);
INSERT INTO tasks VALUES(199,'Use a reusable water bottle for a full day',1);
INSERT INTO tasks VALUES(200,'Learn about one climate-friendly diet option',5);
INSERT INTO tasks VALUES(201,'Turn off extra electronics in a shared space',2);
INSERT INTO tasks VALUES(202,'Plan one zero-waste activity this week',15);
INSERT INTO tasks VALUES(203,'Participate in local environmental webinar',60);
INSERT INTO tasks VALUES(204,'Sort and recycle glass bottles',5);
INSERT INTO tasks VALUES(205,'Collect and separate paper waste',5);
INSERT INTO tasks VALUES(206,'Reflect on energy saved today',2);
INSERT INTO tasks VALUES(207,'Pick up small litter from a bus stop or train station',3);
INSERT INTO tasks VALUES(208,'Use leftover food for composting or creative recipes',5);
INSERT INTO tasks VALUES(209,'Educate someone about climate change impacts',5);
INSERT INTO tasks VALUES(210,'Switch one household product to eco-friendly alternative',5);
INSERT INTO tasks VALUES(211,'Turn off lights in one unused room for a day',1);
INSERT INTO tasks VALUES(212,'Collect and recycle aluminum cans',5);
INSERT INTO tasks VALUES(213,'Pick up trash from a nearby sidewalk',5);
INSERT INTO tasks VALUES(214,'Document one sustainable action you did today',2);
INSERT INTO tasks VALUES(215,'Research sustainable products online',10);
INSERT INTO tasks VALUES(216,'Reflect on ways to reduce carbon footprint this week',5);
INSERT INTO tasks VALUES(217,'Repair or mend clothing instead of discarding',15);
INSERT INTO tasks VALUES(218,'Use a broom instead of hose for outdoor cleaning',5);
INSERT INTO tasks VALUES(219,'Share eco-friendly tips on social media',5);
INSERT INTO tasks VALUES(220,'Turn off water taps when not in use',1);
INSERT INTO tasks VALUES(221,'Pick up litter in a nearby green space',8);
INSERT INTO tasks VALUES(222,'Make a small compost bin for kitchen scraps',15);
INSERT INTO tasks VALUES(223,'Plan one sustainable meal today',5);
INSERT INTO tasks VALUES(224,'Collect recyclable packaging materials at home',5);
INSERT INTO tasks VALUES(225,'Pick up trash along a 50-meter street stretch',3);
INSERT INTO tasks VALUES(226,'Reflect on actions that reduce waste at home',5);
INSERT INTO tasks VALUES(227,'Turn off standby devices for a few hours',2);
INSERT INTO tasks VALUES(228,'Participate in an online tree planting or donation program',60);
INSERT INTO tasks VALUES(229,'Educate a friend about water conservation',5);
INSERT INTO tasks VALUES(230,'Collect small yard debris or leaves for compost',5);
INSERT INTO tasks VALUES(231,'Reflect on eco-friendly habits you practiced this week',5);
INSERT INTO tasks VALUES(232,'Use reusable containers for leftovers',2);
INSERT INTO tasks VALUES(233,'Pick up litter near a local shop or market',5);
INSERT INTO tasks VALUES(234,'Plan a week to reduce household energy usage',10);
INSERT INTO tasks VALUES(235,'Sort recyclable items from trash at home',5);
INSERT INTO tasks VALUES(236,'Pick up microplastics along a short path',10);
INSERT INTO tasks VALUES(237,'Learn one sustainable cooking tip',5);
INSERT INTO tasks VALUES(238,'Share one positive environmental action with friends',2);
INSERT INTO tasks VALUES(239,'Reflect on one way to save water today',1);
INSERT INTO tasks VALUES(240,'Turn off non-essential electronics for the day',3);
INSERT INTO tasks VALUES(241,'Participate in a community recycling initiative',60);
INSERT INTO tasks VALUES(242,'Write a short plan to reduce plastic use this week',10);
INSERT INTO tasks VALUES(243,'Repair small items instead of discarding',15);
INSERT INTO tasks VALUES(244,'Reflect on eco-friendly changes made today',5);
INSERT INTO tasks VALUES(245,'Pick up small litter during a short walk',5);
INSERT INTO tasks VALUES(246,'Use public transport instead of car for one trip',10);
INSERT INTO tasks VALUES(247,'Learn a tip to reduce food waste at home',5);
INSERT INTO tasks VALUES(248,'Turn off extra lights for the day',1);
INSERT INTO tasks VALUES(249,'Sort old papers for recycling',5);
INSERT INTO tasks VALUES(250,'Document eco-friendly actions and plan next week',10);
INSERT INTO tasks VALUES(251,'Reflect on ways to reduce single-use plastics',5);
INSERT INTO tasks VALUES(252,'Use a reusable coffee cup for a day',1);
INSERT INTO tasks VALUES(253,'Pick up trash from nearby streets',5);
INSERT INTO tasks VALUES(254,'Make a short list of eco-friendly habits to adopt',5);
INSERT INTO tasks VALUES(255,'Replace one plastic bag with a reusable bag',1);
INSERT INTO tasks VALUES(256,'Collect leaves or small debris for composting',5);
INSERT INTO tasks VALUES(257,'Participate in an online sustainability workshop',60);
INSERT INTO tasks VALUES(258,'Reflect on energy consumption today',5);
INSERT INTO tasks VALUES(259,'Plan one sustainable shopping choice today',5);
INSERT INTO tasks VALUES(260,'Educate a family member about recycling',5);
INSERT INTO tasks VALUES(261,'Pick up trash along a small park trail',5);
INSERT INTO tasks VALUES(262,'Turn off water while brushing teeth for the day',1);
INSERT INTO tasks VALUES(263,'Reflect on one carbon-saving habit to adopt',5);
INSERT INTO tasks VALUES(264,'Use leftover paper creatively',5);
INSERT INTO tasks VALUES(265,'Repair or upcycle old household items',10);
INSERT INTO tasks VALUES(266,'Reflect on eco-friendly actions for the week',5);
INSERT INTO tasks VALUES(267,'Use reusable containers for storage instead of plastic wrap',2);
INSERT INTO tasks VALUES(268,'Document one eco-friendly action and share with friends',2);
INSERT INTO tasks VALUES(269,'Plan one day to avoid disposable plastics',15);
INSERT INTO tasks VALUES(270,'Participate in virtual tree planting event',60);
INSERT INTO tasks VALUES(271,'Reflect on ways to save water at home',5);
INSERT INTO tasks VALUES(272,'Collect recyclable packaging for proper disposal',5);
INSERT INTO tasks VALUES(273,'Pick up litter during a short neighborhood walk',5);
INSERT INTO tasks VALUES(274,'Share one tip to reduce energy use at home',2);
INSERT INTO tasks VALUES(275,'Turn off unused devices for a few hours',2);
INSERT INTO tasks VALUES(276,'Learn one new eco-friendly habit online',10);
INSERT INTO tasks VALUES(277,'Reflect on household energy-saving measures',5);
INSERT INTO tasks VALUES(278,'Pick up small trash items in your community',5);
INSERT INTO tasks VALUES(279,'Use public transport for one short journey today',10);
INSERT INTO tasks VALUES(280,'Repair clothing instead of discarding',15);
INSERT INTO tasks VALUES(281,'Pick up microplastics or litter in public spaces',10);
INSERT INTO tasks VALUES(282,'Reflect on one small change to reduce waste',5);
INSERT INTO tasks VALUES(283,'Use a reusable mug for drinks',1);
INSERT INTO tasks VALUES(284,'Sort recyclables from trash in the kitchen',5);
INSERT INTO tasks VALUES(285,'Pick up litter along a sidewalk or path',5);
INSERT INTO tasks VALUES(286,'Write down 3 eco-friendly actions to do tomorrow',5);
INSERT INTO tasks VALUES(287,'Turn off lights in empty rooms for the day',1);
INSERT INTO tasks VALUES(288,'Collect small debris or leaves for composting',5);
INSERT INTO tasks VALUES(289,'Participate in an online environmental challenge',60);
INSERT INTO tasks VALUES(290,'Reflect on energy saved this week',5);
INSERT INTO tasks VALUES(291,'Use a reusable shopping bag for all purchases',1);
INSERT INTO tasks VALUES(292,'Learn one tip to reduce carbon footprint today',5);
INSERT INTO tasks VALUES(293,'Pick up small litter in nearby public areas',5);
INSERT INTO tasks VALUES(294,'Reflect on one water-saving action you did',1);
INSERT INTO tasks VALUES(295,'Repair or upcycle a small household item',10);
INSERT INTO tasks VALUES(296,'Participate in virtual sustainability webinar',60);
INSERT INTO tasks VALUES(297,'Sort and recycle old batteries properly',5);
INSERT INTO tasks VALUES(298,'Share a positive eco-friendly action with a friend',2);
INSERT INTO tasks VALUES(299,'Turn off standby electronics for the day',2);
INSERT INTO tasks VALUES(300,'Reflect on eco-friendly habits you maintained',5);
INSERT INTO tasks VALUES(301,'Collect and recycle small metal items',5);
INSERT INTO tasks VALUES(302,'Pick up trash along a short neighborhood walk',5);
INSERT INTO tasks VALUES(303,'Plan a day without single-use plastics',15);
INSERT INTO tasks VALUES(304,'Turn off water heater when not in use for a few hours',5);
INSERT INTO tasks VALUES(305,'Document eco-friendly actions for the week',5);
INSERT INTO tasks VALUES(306,'Replace one disposable item with a sustainable alternative',2);
INSERT INTO tasks VALUES(307,'Reflect on one change to reduce household energy use',5);
INSERT INTO tasks VALUES(308,'Use leftover food creatively instead of discarding',5);
INSERT INTO tasks VALUES(309,'Educate someone about sustainable living',5);
INSERT INTO tasks VALUES(310,'Pick up litter on a 50-meter street stretch',3);
INSERT INTO tasks VALUES(311,'Plan one zero-waste activity for the week',15);
INSERT INTO tasks VALUES(312,'Turn off lights and electronics when not needed for a day',5);
INSERT INTO tasks VALUES(313,'Reflect on 3 eco-friendly habits to adopt',5);
INSERT INTO tasks VALUES(314,'Participate in local recycling drive or initiative',60);
INSERT INTO tasks VALUES(315,'Collect small debris or trash in shared spaces',5);
INSERT INTO tasks VALUES(316,'Pick up microplastics along your route',10);
INSERT INTO tasks VALUES(317,'Plan a sustainable meal to reduce food waste',5);
INSERT INTO tasks VALUES(318,'Reflect on household energy usage and one improvement',5);
INSERT INTO tasks VALUES(319,'Document one eco-friendly action and share online',2);
INSERT INTO tasks VALUES(320,'Turn off water while doing dishes or brushing teeth',1);
INSERT INTO tasks VALUES(321,'Participate in a short online eco-workshop',60);
INSERT INTO tasks VALUES(322,'Repair small clothing or household items instead of discarding',10);
INSERT INTO tasks VALUES(323,'Sort recyclables from trash and properly dispose',5);
INSERT INTO tasks VALUES(324,'Pick up litter along a public path or sidewalk',5);
INSERT INTO tasks VALUES(325,'Reflect on eco-friendly choices you made today',5);
INSERT INTO tasks VALUES(326,'Use reusable containers for storage',2);
INSERT INTO tasks VALUES(327,'Turn off extra lights in your home for the day',1);
INSERT INTO tasks VALUES(328,'Document one carbon-saving habit you did today',2);
INSERT INTO tasks VALUES(329,'Reflect on ways to reduce water and energy usage',5);
INSERT INTO tasks VALUES(330,'Plan one sustainable shopping choice this week',5);
INSERT INTO tasks VALUES(331,'Educate someone about recycling and composting',5);
INSERT INTO tasks VALUES(332,'Pick up trash from local green spaces',5);
INSERT INTO tasks VALUES(333,'Participate in a large-scale online environmental event or tree planting initiative',120);
INSERT INTO tasks VALUES(334,'Research and write a detailed plan for reducing household carbon footprint',100);
INSERT INTO tasks VALUES(335,'Create a list of 50 ways to reduce single-use plastics at home',100);
INSERT INTO tasks VALUES(336,'Organize and sort recyclables from the entire house for proper disposal',100);
INSERT INTO tasks VALUES(337,'Write and share a comprehensive guide on sustainable living online',100);
INSERT INTO tasks VALUES(338,'Participate in an online climate action workshop or webinar',100);
INSERT INTO tasks VALUES(339,'Document and photograph local environmental issues for awareness',100);
INSERT INTO tasks VALUES(340,'Design a small community eco-awareness campaign plan',100);
INSERT INTO tasks VALUES(341,'Research renewable energy options and plan household implementation',100);
INSERT INTO tasks VALUES(342,'Write a blog post or social media thread encouraging sustainability',100);
INSERT INTO tasks VALUES(343,'Plan a week-long zero-waste challenge and track progress',100);
INSERT INTO tasks VALUES(344,'Compile a list of local endangered species and conservation actions',100);
INSERT INTO tasks VALUES(345,'Create a detailed plan to reduce water usage in your home',100);
INSERT INTO tasks VALUES(346,'Organize a virtual swap or donation event with friends/family',100);
INSERT INTO tasks VALUES(347,'Create educational material about recycling and composting',100);
INSERT INTO tasks VALUES(348,'Research and plan ways to reduce carbon footprint from transportation',100);
INSERT INTO tasks VALUES(349,'Write a comprehensive plan for a personal or household energy audit',100);
INSERT INTO tasks VALUES(350,'Design a poster or infographic about climate change and share online',100);
INSERT INTO tasks VALUES(351,'Organize and clean up a public park or local green space',100);
INSERT INTO tasks VALUES(352,'Plan a week-long sustainable meal plan to reduce food waste',100);
INSERT INTO tasks VALUES(353,'Research and write about local environmental laws and policies',100);
INSERT INTO tasks VALUES(354,'Compile a list of eco-friendly alternatives to daily products',100);
INSERT INTO tasks VALUES(355,'Organize a small volunteer drive for a local environmental NGO',100);
INSERT INTO tasks VALUES(356,'Write a detailed guide on reducing single-use plastics in the community',100);
INSERT INTO tasks VALUES(357,'Document and share tips to save energy in households',100);
INSERT INTO tasks VALUES(358,'Create an awareness campaign for water conservation in your area',100);
INSERT INTO tasks VALUES(359,'Plan and document actions to reduce personal carbon footprint this month',100);
INSERT INTO tasks VALUES(360,'Create a video or slideshow educating people on biodiversity',100);
INSERT INTO tasks VALUES(361,'Compile a list of local environmental challenges and solutions',100);
INSERT INTO tasks VALUES(362,'Organize a community clean-up event with proper safety measures',100);
INSERT INTO tasks VALUES(363,'Research innovative ways to reduce household waste',100);
INSERT INTO tasks VALUES(364,'Create a digital guide on sustainable travel options',100);
INSERT INTO tasks VALUES(365,'Document one month of eco-friendly actions in a personal journal',100);
INSERT INTO tasks VALUES(366,'Plan and execute a neighborhood recycling awareness campaign',100);
INSERT INTO tasks VALUES(367,'Compile a list of sustainable practices for schools or offices',100);
INSERT INTO tasks VALUES(368,'Organize a digital presentation for friends on climate change',100);
INSERT INTO tasks VALUES(369,'Research and plan a small-scale urban gardening project',100);
INSERT INTO tasks VALUES(370,'Write a report on local air pollution sources and solutions',100);
INSERT INTO tasks VALUES(371,'Create a step-by-step plan to reduce single-use plastics at work',100);
INSERT INTO tasks VALUES(372,'Document and photograph local wildlife to raise awareness',100);
INSERT INTO tasks VALUES(373,'Organize digital resources for eco-friendly habits at home',100);
INSERT INTO tasks VALUES(374,'Plan and document steps for a personal zero-waste month',100);
INSERT INTO tasks VALUES(375,'Research and write about renewable energy solutions for households',100);
INSERT INTO tasks VALUES(376,'Create a social media plan to encourage sustainable habits',100);
INSERT INTO tasks VALUES(377,'Document a week of energy-saving actions in the household',100);
INSERT INTO tasks VALUES(378,'Organize a local clean-up event and invite neighbors',100);
INSERT INTO tasks VALUES(379,'Compile a list of low-carbon diet recipes for a week',100);
INSERT INTO tasks VALUES(380,'Research ways to reduce packaging waste from online purchases',100);
INSERT INTO tasks VALUES(381,'Write a detailed guide for reducing water footprint in daily life',100);
INSERT INTO tasks VALUES(382,'Plan and document a personal sustainable transportation challenge',100);
INSERT INTO tasks VALUES(383,'Research eco-friendly alternatives for common household products',100);
INSERT INTO tasks VALUES(384,'Create a digital poster campaign on reducing household energy use',100);
INSERT INTO tasks VALUES(385,'Organize a virtual discussion on environmental issues with friends',100);
INSERT INTO tasks VALUES(386,'Document sustainable practices in your neighborhood',100);
INSERT INTO tasks VALUES(387,'Plan and implement a personal clothing sustainability challenge',100);
INSERT INTO tasks VALUES(388,'Compile tips for reducing single-use plastics for community sharing',100);
INSERT INTO tasks VALUES(389,'Research and document ways to reduce food waste in households',100);
INSERT INTO tasks VALUES(390,'Create a detailed checklist for eco-friendly home upgrades',100);
INSERT INTO tasks VALUES(391,'Plan a personal carbon footprint reduction challenge',100);
INSERT INTO tasks VALUES(392,'Organize digital resources to educate others on climate action',100);
INSERT INTO tasks VALUES(393,'Document a week-long plan to reduce electricity usage',100);
INSERT INTO tasks VALUES(394,'Research and plan sustainable water usage in the home',100);
INSERT INTO tasks VALUES(395,'Create a guide for eco-friendly commuting methods',100);
INSERT INTO tasks VALUES(396,'Plan and track personal actions to support local biodiversity',100);
INSERT INTO tasks VALUES(397,'Document and share 50 small actions for a greener lifestyle',100);
INSERT INTO tasks VALUES(398,'Organize a digital campaign to encourage recycling at work',100);
INSERT INTO tasks VALUES(399,'Research and plan one month of sustainable shopping',100);
INSERT INTO tasks VALUES(400,'Write a comprehensive report on reducing home energy use',100);
INSERT INTO tasks VALUES(401,'Plan a week of activities focused on reducing carbon emissions',100);
INSERT INTO tasks VALUES(402,'Compile a list of online resources for sustainable living',100);
INSERT INTO tasks VALUES(403,'Create a personal guide for reducing waste at home',100);
INSERT INTO tasks VALUES(404,'Document steps to reduce personal water usage for a month',100);
INSERT INTO tasks VALUES(405,'Plan a small campaign to encourage energy-saving habits',100);
INSERT INTO tasks VALUES(406,'Research and document ways to reduce transportation emissions',100);
INSERT INTO tasks VALUES(407,'Organize a personal or group digital sustainability challenge',100);
INSERT INTO tasks VALUES(408,'Create educational content for local environmental awareness',100);
INSERT INTO tasks VALUES(409,'Plan a week of zero-waste activities and track progress',100);
INSERT INTO tasks VALUES(410,'Document and share tips for reducing electricity consumption',100);
INSERT INTO tasks VALUES(411,'Research ways to reduce plastic packaging waste',100);
INSERT INTO tasks VALUES(412,'Compile a detailed plan to improve personal sustainability habits',100);
INSERT INTO tasks VALUES(413,'Plan and track a month of personal carbon reduction actions',100);
INSERT INTO tasks VALUES(414,'Create a guide for low-energy lifestyle habits',100);
INSERT INTO tasks VALUES(415,'Organize digital materials to educate others on climate-friendly practices',100);
INSERT INTO tasks VALUES(416,'Document a week of sustainable meal planning',100);
INSERT INTO tasks VALUES(417,'Research ways to reduce household heating and cooling energy',100);
INSERT INTO tasks VALUES(418,'Plan a month-long personal eco-friendly challenge',100);
INSERT INTO tasks VALUES(419,'Compile a list of eco-friendly household products',100);
INSERT INTO tasks VALUES(420,'Create an infographic on ways to reduce carbon footprint',100);
INSERT INTO tasks VALUES(421,'Document steps for sustainable waste disposal at home',100);
INSERT INTO tasks VALUES(422,'Plan and track personal energy-saving activities for a week',100);
INSERT INTO tasks VALUES(423,'Research and create a guide for water-efficient habits',100);
INSERT INTO tasks VALUES(424,'Organize a digital event for friends/family on climate awareness',100);
INSERT INTO tasks VALUES(425,'Compile and share tips to reduce household electricity usage',100);
INSERT INTO tasks VALUES(426,'Document actions to reduce food waste for one month',100);
INSERT INTO tasks VALUES(427,'Plan a detailed carbon reduction schedule for personal activities',100);
INSERT INTO tasks VALUES(428,'Research sustainable alternatives to single-use plastics',100);
INSERT INTO tasks VALUES(429,'Create a week-long plan to conserve water and energy',100);
INSERT INTO tasks VALUES(430,'Document eco-friendly transportation options available locally',100);
INSERT INTO tasks VALUES(431,'Plan and track personal zero-waste activities for a month',100);
INSERT INTO tasks VALUES(432,'Compile a list of practical energy-saving tips',100);
INSERT INTO tasks VALUES(433,'Organize online resources for climate-conscious living',100);
INSERT INTO tasks VALUES(434,'Document steps to improve home energy efficiency',100);
INSERT INTO tasks VALUES(435,'Plan a sustainable lifestyle challenge for 30 days',100);
INSERT INTO tasks VALUES(436,'Research and document ways to reduce personal carbon footprint',100);
INSERT INTO tasks VALUES(437,'Create digital content to raise awareness about climate change',100);
INSERT INTO tasks VALUES(438,'Compile tips for reducing food packaging waste',100);
INSERT INTO tasks VALUES(439,'Plan and execute one week of energy-saving activities',100);
INSERT INTO tasks VALUES(440,'Document sustainable habits to maintain for a month',100);
INSERT INTO tasks VALUES(441,'Organize a virtual sustainability workshop for friends/family',100);
INSERT INTO tasks VALUES(442,'Research personal energy consumption and ways to reduce it',100);
INSERT INTO tasks VALUES(443,'Create a digital guide for eco-friendly daily routines',100);
INSERT INTO tasks VALUES(444,'Document and plan personal actions to reduce water usage',100);
INSERT INTO tasks VALUES(445,'Plan and track one month of zero-waste activities',100);
INSERT INTO tasks VALUES(446,'Compile tips for eco-friendly commuting habits',100);
INSERT INTO tasks VALUES(447,'Create content to raise awareness about single-use plastic pollution',100);
INSERT INTO tasks VALUES(448,'Document personal carbon-saving actions for a week',100);
INSERT INTO tasks VALUES(449,'Plan a month-long challenge to reduce electricity usage',100);
INSERT INTO tasks VALUES(450,'Organize a virtual discussion about sustainable living practices',100);
INSERT INTO tasks VALUES(451,'Research and plan ways to reduce plastic consumption',100);
INSERT INTO tasks VALUES(452,'Create a checklist for eco-friendly home improvements',100);
INSERT INTO tasks VALUES(453,'Document personal sustainable practices for a month',100);
INSERT INTO tasks VALUES(454,'Plan and track eco-friendly meal preparation for one month',100);
INSERT INTO tasks VALUES(455,'Compile tips for reducing energy usage in everyday life',100);
INSERT INTO tasks VALUES(456,'Create digital material to educate others on sustainable actions',100);
INSERT INTO tasks VALUES(457,'Document a week-long plan for reducing personal waste',100);
INSERT INTO tasks VALUES(458,'Plan a personal challenge to minimize single-use plastic for a month',100);
INSERT INTO tasks VALUES(459,'Organize a virtual eco-awareness campaign for friends/family',100);
INSERT INTO tasks VALUES(460,'Research sustainable products for personal and household use',100);
INSERT INTO tasks VALUES(461,'Create a detailed month-long plan for energy and water conservation',100);
INSERT INTO tasks VALUES(462,'Document tips and actions to reduce household carbon footprint',100);
INSERT INTO tasks VALUES(463,'Plan a week of activities to reduce personal environmental impact',100);
INSERT INTO tasks VALUES(464,'Compile a list of practical ways to conserve energy at home',100);
INSERT INTO tasks VALUES(465,'Create content to encourage sustainable practices in your community',100);
INSERT INTO tasks VALUES(466,'Document and plan zero-waste lifestyle activities',100);
INSERT INTO tasks VALUES(467,'Plan and track a month of low-energy lifestyle habits',100);
INSERT INTO tasks VALUES(468,'Organize online resources to educate about reducing environmental impact',100);
INSERT INTO tasks VALUES(469,'Research and document personal transportation carbon reduction strategies',100);
INSERT INTO tasks VALUES(470,'Create a detailed plan for minimizing household waste for a month',100);
INSERT INTO tasks VALUES(471,'Document steps to reduce energy and water consumption daily',100);
INSERT INTO tasks VALUES(472,'Plan and execute personal actions to lower carbon emissions',100);
INSERT INTO tasks VALUES(473,'Compile tips for sustainable daily habits and routines',100);
INSERT INTO tasks VALUES(474,'Create an infographic for climate-friendly lifestyle tips',100);
INSERT INTO tasks VALUES(475,'Document a month of energy-saving household actions',100);
INSERT INTO tasks VALUES(476,'Plan a week-long challenge to reduce single-use plastics',100);
INSERT INTO tasks VALUES(477,'Organize virtual content to educate others about sustainable living',100);
INSERT INTO tasks VALUES(478,'Research and document eco-friendly alternatives to daily products',100);
INSERT INTO tasks VALUES(479,'Create a detailed checklist for zero-waste and energy-saving activities',100);
INSERT INTO tasks VALUES(480,'Document personal sustainable actions for one month',100);
INSERT INTO tasks VALUES(481,'Plan a week of activities to reduce water and energy use',100);
INSERT INTO tasks VALUES(482,'Compile tips for minimizing personal carbon footprint',100);
INSERT INTO tasks VALUES(483,'Create content to inspire sustainable practices online',100);
INSERT INTO tasks VALUES(484,'Document steps to reduce household energy and waste',100);
INSERT INTO tasks VALUES(485,'Plan a month-long personal challenge to live sustainably',100);
INSERT INTO tasks VALUES(486,'Organize digital resources to encourage eco-conscious habits',100);
INSERT INTO tasks VALUES(487,'Research and document ways to reduce plastic use daily',100);
INSERT INTO tasks VALUES(488,'Create a plan for a sustainable and low-carbon lifestyle',100);
INSERT INTO tasks VALUES(489,'Document and track energy-saving actions for a month',100);
INSERT INTO tasks VALUES(490,'Plan a week of sustainable commuting and transportation choices',100);
INSERT INTO tasks VALUES(491,'Compile tips for reducing water and energy usage at home',100);
INSERT INTO tasks VALUES(492,'Create content to raise awareness of sustainable living practices',100);
INSERT INTO tasks VALUES(493,'Document a month of actions to reduce household environmental impact',100);
INSERT INTO tasks VALUES(494,'Plan a personal zero-waste and low-energy month',100);
INSERT INTO tasks VALUES(495,'Organize a virtual awareness campaign on climate change',100);
INSERT INTO tasks VALUES(496,'Research and document eco-friendly alternatives for household items',100);
INSERT INTO tasks VALUES(497,'Create a checklist of actions for reducing household carbon footprint',100);
INSERT INTO tasks VALUES(498,'Document and plan energy-saving and waste-reduction activities',100);
INSERT INTO tasks VALUES(499,'Plan a month-long challenge for sustainable living habits',100);
INSERT INTO tasks VALUES(500,'Compile tips for low-energy cooking and lifestyle choices',100);
INSERT INTO tasks VALUES(501,'Create content to educate others on eco-friendly practices',100);
INSERT INTO tasks VALUES(502,'Document and track sustainable actions for personal accountability',100);
INSERT INTO tasks VALUES(503,'Plan and execute personal actions to minimize environmental impact',100);
INSERT INTO tasks VALUES(504,'Research ways to reduce household water consumption',100);
INSERT INTO tasks VALUES(505,'Create a week-long challenge for low-waste living',100);
INSERT INTO tasks VALUES(506,'Document tips and actions for energy-efficient lifestyle',100);
INSERT INTO tasks VALUES(507,'Plan a detailed personal sustainability challenge for 30 days',100);
INSERT INTO tasks VALUES(508,'Organize virtual resources to educate friends/family on eco-friendly habits',100);
INSERT INTO tasks VALUES(509,'Research and document carbon footprint reduction strategies',100);
INSERT INTO tasks VALUES(510,'Create a checklist for zero-waste, low-energy, and water-saving actions',100);
INSERT INTO tasks VALUES(511,'Document and track eco-friendly habits for a month',100);
INSERT INTO tasks VALUES(512,'Plan a month of activities to reduce single-use plastics and waste',100);
INSERT INTO tasks VALUES(513,'Compile tips for sustainable shopping and daily habits',100);
INSERT INTO tasks VALUES(514,'Create digital content to inspire climate-conscious lifestyle',100);
INSERT INTO tasks VALUES(515,'Document steps to reduce energy, water, and waste at home',100);
INSERT INTO tasks VALUES(516,'Plan a personal eco-challenge for one month',100);
INSERT INTO tasks VALUES(517,'Organize virtual workshops on sustainable living for friends/family',100);
INSERT INTO tasks VALUES(518,'Research and document ways to reduce household carbon footprint',100);
INSERT INTO tasks VALUES(519,'Create a guide for low-waste and energy-saving practices',100);
INSERT INTO tasks VALUES(520,'Document personal sustainable actions to track progress',100);
INSERT INTO tasks VALUES(521,'Plan a week of activities focused on water and energy conservation',100);
INSERT INTO tasks VALUES(522,'Compile tips to reduce personal and household environmental impact',100);
INSERT INTO tasks VALUES(523,'Create digital material for raising awareness about climate change',100);
INSERT INTO tasks VALUES(524,'Document steps for a sustainable lifestyle challenge',100);
INSERT INTO tasks VALUES(525,'Plan a month-long personal challenge to live more sustainably',100);
INSERT INTO tasks VALUES(526,'Organize online resources for friends/family to adopt eco-friendly habits',100);
INSERT INTO tasks VALUES(527,'Research and document low-energy alternatives for common household items',100);
INSERT INTO tasks VALUES(528,'Create a checklist for eco-friendly and sustainable living actions',100);
INSERT INTO tasks VALUES(529,'Document and track personal zero-waste, low-energy, and water-saving habits',100);
INSERT INTO tasks VALUES(530,'Plan a month-long challenge to reduce household carbon footprint',100);
INSERT INTO tasks VALUES(531,'Compile tips for reducing personal environmental impact at home',100);
INSERT INTO tasks VALUES(532,'Create content to encourage sustainable practices in your circle',100);
INSERT INTO tasks VALUES(533,'Document and plan sustainable actions to maintain for one month',100);
INSERT INTO tasks VALUES(534,'Plan a week-long challenge to adopt energy-saving habits',100);
INSERT INTO tasks VALUES(535,'Organize digital resources to educate others on climate-friendly practices',100);
INSERT INTO tasks VALUES(536,'Research and document sustainable food choices and habits',100);
INSERT INTO tasks VALUES(537,'Create a guide to reduce household waste and save energy',100);
INSERT INTO tasks VALUES(538,'Document personal actions to minimize environmental impact for a month',100);
INSERT INTO tasks VALUES(539,'Plan a detailed month-long eco-challenge for sustainable living',100);
INSERT INTO tasks VALUES(540,'Compile tips for reducing carbon emissions in daily life',100);
INSERT INTO tasks VALUES(541,'Create content to inspire eco-conscious behavior in your community',100);
INSERT INTO tasks VALUES(542,'Document a month of energy, water, and waste-saving actions',100);
INSERT INTO tasks VALUES(543,'Plan and track zero-waste and low-energy lifestyle actions',100);
INSERT INTO tasks VALUES(544,'Organize online campaigns or posts to promote sustainability',100);
INSERT INTO tasks VALUES(545,'Research and document eco-friendly habits for household use',100);
INSERT INTO tasks VALUES(546,'Create a comprehensive plan for reducing personal carbon footprint',100);
INSERT INTO tasks VALUES(547,'Document sustainable actions and progress for accountability',100);
INSERT INTO tasks VALUES(548,'Plan a month-long sustainable living challenge',100);
INSERT INTO tasks VALUES(549,'Compile tips for adopting eco-friendly daily habits',100);
INSERT INTO tasks VALUES(550,'Create content to educate friends/family about reducing environmental impact',100);
INSERT INTO tasks VALUES(551,'Document steps to reduce household energy and waste usage',100);
INSERT INTO tasks VALUES(552,'Plan a personal challenge to reduce carbon and water footprint',100);
INSERT INTO tasks VALUES(553,'Organize virtual awareness sessions for sustainable living',100);
INSERT INTO tasks VALUES(554,'Research and document ways to reduce plastic, water, and energy usage',100);
INSERT INTO tasks VALUES(555,'Create a detailed personal plan for eco-friendly lifestyle habits',100);
INSERT INTO tasks VALUES(556,'Document and track eco-friendly actions daily for a month',100);
INSERT INTO tasks VALUES(557,'Plan and execute personal sustainability initiatives',100);
INSERT INTO tasks VALUES(558,'Compile tips for low-carbon living in everyday routines',100);
INSERT INTO tasks VALUES(559,'Create content to raise awareness about sustainable practices',100);
INSERT INTO tasks VALUES(560,'Document steps for a month-long zero-waste challenge',100);
INSERT INTO tasks VALUES(561,'Plan a week-long eco-conscious action plan',100);
INSERT INTO tasks VALUES(562,'Organize online guides and resources for sustainable habits',100);
INSERT INTO tasks VALUES(563,'Research and document ways to live a low-energy lifestyle',100);
INSERT INTO tasks VALUES(564,'Create a checklist for eco-friendly actions to maintain daily',100);
INSERT INTO tasks VALUES(565,'Document and track personal energy, water, and waste savings',100);
INSERT INTO tasks VALUES(566,'Plan a month of zero-waste, low-energy, and water-saving activities',100);
INSERT INTO tasks VALUES(567,'Compile tips for adopting sustainable practices at home',100);
INSERT INTO tasks VALUES(568,'Create digital content to inspire eco-friendly choices',100);
INSERT INTO tasks VALUES(569,'Document a month of sustainable living actions and results',100);
INSERT INTO tasks VALUES(570,'Plan and track one month of energy, water, and waste-saving actions',100);
INSERT INTO tasks VALUES(571,'Organize online campaigns to promote sustainability awareness',100);
INSERT INTO tasks VALUES(572,'Research and document ways to reduce environmental impact in daily life',100);
INSERT INTO tasks VALUES(573,'Create a guide for personal eco-friendly practices',100);
INSERT INTO tasks VALUES(574,'Document steps to implement sustainable living routines',100);
INSERT INTO tasks VALUES(575,'Plan a month-long challenge to adopt eco-conscious habits',100);
INSERT INTO tasks VALUES(576,'Compile tips for reducing carbon, water, and waste footprints',100);
INSERT INTO tasks VALUES(577,'Create content to encourage sustainability within your network',100);
INSERT INTO tasks VALUES(578,'Document actions and results of eco-friendly lifestyle habits',100);
INSERT INTO tasks VALUES(579,'Plan and execute one month of zero-waste activities',100);
INSERT INTO tasks VALUES(580,'Organize digital resources to educate about low-energy living',100);
INSERT INTO tasks VALUES(581,'Research and document practical ways to reduce environmental impact',100);
INSERT INTO tasks VALUES(582,'Create a detailed plan for adopting sustainable daily habits',100);
INSERT INTO tasks VALUES(583,'Document and track eco-conscious lifestyle choices for a month',100);
INSERT INTO tasks VALUES(584,'Plan a personal challenge to live sustainably for 30 days',100);
INSERT INTO tasks VALUES(585,'Compile tips to reduce personal energy and water usage',100);
INSERT INTO tasks VALUES(586,'Create content to raise awareness about eco-friendly habits',100);
INSERT INTO tasks VALUES(587,'Document steps to improve sustainability in daily routines',100);
INSERT INTO tasks VALUES(588,'Plan a month-long zero-waste and low-energy lifestyle plan',100);
INSERT INTO tasks VALUES(589,'Organize virtual guides or workshops for sustainable living',100);
INSERT INTO tasks VALUES(590,'Research and document ways to reduce environmental impact at home',100);
INSERT INTO tasks VALUES(591,'Create a checklist for eco-friendly and sustainable daily habits',100);
INSERT INTO tasks VALUES(592,'Document and track personal actions to reduce household carbon footprint',100);
INSERT INTO tasks VALUES(593,'Plan and execute one month of eco-friendly lifestyle activities',100);
INSERT INTO tasks VALUES(594,'Compile tips for adopting low-energy and zero-waste habits',100);
INSERT INTO tasks VALUES(595,'Create content to inspire sustainable living practices',100);
INSERT INTO tasks VALUES(596,'Document steps to reduce household energy, water, and waste',100);
INSERT INTO tasks VALUES(597,'Plan a month-long challenge for adopting sustainable habits',100);
INSERT INTO tasks VALUES(598,'Organize online resources to educate others about eco-friendly living',100);
INSERT INTO tasks VALUES(599,'Research and document low-carbon and low-waste lifestyle practices',100);
INSERT INTO tasks VALUES(600,'Create a detailed guide for personal sustainable living',100);
INSERT INTO tasks VALUES(601,'Document and track zero-waste, low-energy, and water-saving actions',100);
INSERT INTO tasks VALUES(602,'Plan a month of eco-conscious activities and track results',100);
INSERT INTO tasks VALUES(603,'Compile tips for reducing environmental impact at home',100);
INSERT INTO tasks VALUES(604,'Create content to raise awareness about sustainable daily habits',100);
INSERT INTO tasks VALUES(605,'Document steps to maintain eco-friendly routines for a month',100);
INSERT INTO tasks VALUES(606,'Plan and track one month of energy, water, and waste-saving actions',100);
INSERT INTO tasks VALUES(607,'Organize virtual awareness content for sustainable lifestyle adoption',100);
INSERT INTO tasks VALUES(608,'Research and document ways to adopt low-energy and low-waste habits',100);
INSERT INTO tasks VALUES(609,'Create a checklist for adopting sustainable living practices',100);
INSERT INTO tasks VALUES(610,'Document and track eco-friendly actions and results for one month',100);
INSERT INTO tasks VALUES(611,'Plan a personal challenge to reduce household carbon footprint for a month',100);
INSERT INTO tasks VALUES(612,'Compile tips for sustainable practices at work, school, or home',100);
INSERT INTO tasks VALUES(613,'Create content to educate about eco-friendly lifestyle habits',100);
INSERT INTO tasks VALUES(614,'Document steps to improve sustainability and reduce environmental impact',100);
INSERT INTO tasks VALUES(615,'Plan a month-long challenge to adopt zero-waste and low-energy habits',100);
INSERT INTO tasks VALUES(616,'Organize online guides and content for friends/family to live sustainably',100);
INSERT INTO tasks VALUES(617,'Research and document eco-friendly alternatives to common items',100);
INSERT INTO tasks VALUES(618,'Create a detailed plan for low-carbon and sustainable living',100);
INSERT INTO tasks VALUES(619,'Document and track actions for eco-conscious living for a month',100);
INSERT INTO tasks VALUES(620,'Plan a week-long challenge to reduce energy, water, and waste usage',100);
INSERT INTO tasks VALUES(621,'Compile tips for reducing household carbon footprint',100);
INSERT INTO tasks VALUES(622,'Create content to inspire friends/family to adopt sustainable habits',100);
INSERT INTO tasks VALUES(623,'Document steps to adopt zero-waste, low-energy, and water-saving routines',100);
INSERT INTO tasks VALUES(624,'Plan a month-long personal eco-challenge',100);
INSERT INTO tasks VALUES(625,'Organize digital resources for sustainable living awareness',100);
INSERT INTO tasks VALUES(626,'Research and document ways to reduce environmental impact daily',100);
INSERT INTO tasks VALUES(627,'Create a checklist for eco-friendly daily practices',100);
INSERT INTO tasks VALUES(628,'Document and track personal zero-waste and low-energy habits',100);
INSERT INTO tasks VALUES(629,'Plan and track one month of sustainable living actions',100);
INSERT INTO tasks VALUES(630,'Compile tips for eco-conscious lifestyle adoption',100);
INSERT INTO tasks VALUES(631,'Create content to encourage friends/family to live sustainably',100);
INSERT INTO tasks VALUES(632,'Document steps to reduce household energy, water, and waste footprint',100);
INSERT INTO tasks VALUES(633,'Plan a detailed month-long zero-waste and low-energy challenge',100);
INSERT INTO tasks VALUES(634,'Organize virtual awareness campaigns to educate others about sustainability',100);
INSERT INTO tasks VALUES(635,'Research and document practical eco-friendly habits for daily life',100);
INSERT INTO tasks VALUES(636,'Create a guide for adopting sustainable living habits',100);
INSERT INTO tasks VALUES(637,'Document and track personal sustainable actions and results',100);
INSERT INTO tasks VALUES(638,'Plan a month-long challenge to adopt eco-friendly habits',100);
INSERT INTO tasks VALUES(639,'Compile tips to reduce carbon, water, and waste usage',100);
INSERT INTO tasks VALUES(640,'Create content to raise awareness of low-energy and zero-waste lifestyle',100);
INSERT INTO tasks VALUES(641,'Document steps to improve sustainability in personal routines',100);
INSERT INTO tasks VALUES(642,'Plan and execute one month of eco-conscious lifestyle activities',100);
INSERT INTO tasks VALUES(643,'Organize online guides and campaigns for sustainable living',100);
INSERT INTO tasks VALUES(644,'Research and document ways to minimize environmental impact',100);
INSERT INTO tasks VALUES(645,'Create a checklist for zero-waste, low-energy, and water-saving actions',100);
INSERT INTO tasks VALUES(646,'Document and track eco-friendly actions for a month',100);
INSERT INTO tasks VALUES(647,'Plan a month-long challenge for sustainable habits adoption',100);
INSERT INTO tasks VALUES(648,'Compile tips for reducing personal and household environmental impact',100);
INSERT INTO tasks VALUES(649,'Create content to educate friends/family about eco-friendly practices',100);
INSERT INTO tasks VALUES(650,'Document steps to reduce energy, water, and waste for one month',100);
INSERT INTO tasks VALUES(651,'Plan and track personal eco-challenges for a month',100);
INSERT INTO tasks VALUES(652,'Organize digital resources for sustainability awareness',100);
INSERT INTO tasks VALUES(653,'Research and document ways to adopt low-carbon and low-waste practices',100);
INSERT INTO tasks VALUES(654,'Create a detailed plan for a sustainable lifestyle challenge',100);
INSERT INTO tasks VALUES(655,'Document and track personal zero-waste and eco-friendly habits',100);
INSERT INTO tasks VALUES(656,'Plan a month of eco-conscious actions and track results',100);
INSERT INTO tasks VALUES(657,'Compile tips for adopting sustainable practices daily',100);
INSERT INTO tasks VALUES(658,'Create content to inspire eco-conscious behavior in your network',100);
INSERT INTO tasks VALUES(659,'Document steps to implement eco-friendly habits for a month',100);
INSERT INTO tasks VALUES(660,'Plan a month-long challenge to reduce personal environmental impact',100);
INSERT INTO tasks VALUES(661,'Organize online resources and guides for sustainable lifestyle',100);
INSERT INTO tasks VALUES(662,'Research and document practical ways to adopt eco-friendly habits',100);
INSERT INTO tasks VALUES(663,'Create a checklist for sustainable daily routines',100);
INSERT INTO tasks VALUES(664,'Document and track personal actions for eco-friendly living',100);
INSERT INTO tasks VALUES(665,'Plan a detailed month-long zero-waste and low-energy challenge',100);
INSERT INTO tasks VALUES(666,'Compile tips for sustainable lifestyle adoption in everyday life',100);
INSERT INTO tasks VALUES(667,'Create content to educate friends/family on eco-friendly practices',100);
INSERT INTO tasks VALUES(668,'Document steps to reduce environmental impact for one month',100);
INSERT INTO tasks VALUES(669,'Plan and execute personal eco-friendly lifestyle actions for a month',100);
INSERT INTO tasks VALUES(670,'Organize virtual awareness content to encourage sustainability',100);
INSERT INTO tasks VALUES(671,'Research and document ways to live sustainably in daily life',100);
INSERT INTO tasks VALUES(672,'Create a guide for personal zero-waste and low-energy habits',100);
INSERT INTO tasks VALUES(673,'Document and track actions to reduce carbon, water, and waste',100);
INSERT INTO tasks VALUES(674,'Plan a month-long challenge for adopting eco-conscious habits',100);
INSERT INTO tasks VALUES(675,'Compile tips for low-energy and zero-waste practices at home',100);
INSERT INTO tasks VALUES(676,'Create content to inspire sustainable daily routines',100);
INSERT INTO tasks VALUES(677,'Document steps to implement eco-friendly actions for a month',100);
INSERT INTO tasks VALUES(678,'Plan and track one month of sustainable lifestyle actions',100);
INSERT INTO tasks VALUES(679,'Organize online resources for friends/family to adopt eco-conscious habits',100);
INSERT INTO tasks VALUES(680,'Research and document ways to reduce environmental footprint daily',100);
INSERT INTO tasks VALUES(681,'Create a checklist for sustainable lifestyle and zero-waste actions',100);
INSERT INTO tasks VALUES(682,'Document and track eco-friendly habits for one month',100);
INSERT INTO tasks VALUES(683,'Plan a month-long challenge to reduce personal carbon footprint',100);
INSERT INTO tasks VALUES(684,'Compile tips to adopt sustainable and low-energy lifestyle',100);
INSERT INTO tasks VALUES(685,'Create content to educate about eco-friendly daily habits',100);
INSERT INTO tasks VALUES(686,'Document steps to reduce household energy, water, and waste',100);
INSERT INTO tasks VALUES(687,'Plan and execute one month of personal eco-friendly habits',100);
INSERT INTO tasks VALUES(688,'Organize digital resources for sustainable living awareness',100);
INSERT INTO tasks VALUES(689,'Research and document practical ways to reduce environmental impact',100);
INSERT INTO tasks VALUES(690,'Create a detailed plan for adopting low-carbon lifestyle habits',100);
INSERT INTO tasks VALUES(691,'Document and track sustainable living actions for a month',100);
INSERT INTO tasks VALUES(692,'Plan a month-long challenge to adopt eco-friendly lifestyle habits',100);
INSERT INTO tasks VALUES(693,'Compile tips for sustainable daily routines and practices',100);
INSERT INTO tasks VALUES(694,'Create content to inspire friends/family to live sustainably',100);
INSERT INTO tasks VALUES(695,'Document steps to implement zero-waste and eco-friendly habits',100);
INSERT INTO tasks VALUES(696,'Plan and track personal eco-conscious lifestyle actions for one month',100);
INSERT INTO tasks VALUES(697,'Organize online guides and campaigns for sustainable living awareness',100);
INSERT INTO tasks VALUES(698,'Research and document ways to adopt low-waste, low-energy habits',100);
INSERT INTO tasks VALUES(699,'Create a checklist for sustainable and eco-friendly daily actions',100);
INSERT INTO tasks VALUES(700,'Document and track personal eco-friendly actions for accountability',100);
INSERT INTO tasks VALUES(701,'Plan a month-long personal challenge to reduce environmental impact',100);
INSERT INTO tasks VALUES(702,'Compile tips for adopting sustainable habits daily',100);
INSERT INTO tasks VALUES(703,'Create content to educate friends/family about eco-friendly routines',100);
INSERT INTO tasks VALUES(704,'Document steps to reduce household carbon, water, and waste footprint',100);
INSERT INTO tasks VALUES(705,'Plan and execute a month of zero-waste and low-energy lifestyle activities',100);
INSERT INTO tasks VALUES(706,'Organize digital resources to educate others on sustainability',100);
INSERT INTO tasks VALUES(707,'Research and document ways to adopt eco-conscious habits',100);
INSERT INTO tasks VALUES(708,'Create a detailed plan for sustainable living and low-carbon practices',100);
INSERT INTO tasks VALUES(709,'Document and track personal zero-waste and eco-friendly habits',100);
INSERT INTO tasks VALUES(710,'Plan a month of eco-conscious actions and track results',100);
INSERT INTO tasks VALUES(711,'Compile tips for adopting sustainable practices at home',100);
INSERT INTO tasks VALUES(712,'Create content to inspire sustainable behavior online',100);
INSERT INTO tasks VALUES(713,'Document steps to implement low-energy, zero-waste routines',100);
INSERT INTO tasks VALUES(714,'Plan a month-long challenge for personal sustainable habits',100);
INSERT INTO tasks VALUES(715,'Organize online guides and resources for sustainable living',100);
INSERT INTO tasks VALUES(716,'Research and document ways to minimize environmental impact',100);
INSERT INTO tasks VALUES(717,'Create a checklist for eco-friendly and sustainable living actions',100);
INSERT INTO tasks VALUES(718,'Document and track personal actions for a month',100);
INSERT INTO tasks VALUES(719,'Plan and execute a month of zero-waste, low-energy, and sustainable habits',100);
INSERT INTO tasks VALUES(720,'Compile tips for adopting eco-conscious lifestyle habits',100);
INSERT INTO tasks VALUES(721,'Create content to educate friends/family about sustainable living',100);
INSERT INTO tasks VALUES(722,'Document steps to reduce household energy, water, and waste',100);
INSERT INTO tasks VALUES(723,'Plan a detailed month-long challenge to adopt sustainable lifestyle',100);
INSERT INTO tasks VALUES(724,'Organize virtual awareness campaigns to promote eco-friendly habits',100);
INSERT INTO tasks VALUES(725,'Research and document ways to live a sustainable, low-energy lifestyle',100);
INSERT INTO tasks VALUES(726,'Create a guide for personal zero-waste and energy-saving habits',100);
INSERT INTO tasks VALUES(727,'Document and track actions to reduce environmental impact for one month',100);
INSERT INTO tasks VALUES(728,'Plan a month-long personal challenge to live sustainably',100);
INSERT INTO tasks VALUES(729,'Compile tips for reducing household carbon, water, and energy usage',100);
INSERT INTO tasks VALUES(730,'Create content to inspire eco-conscious habits in friends/family',100);
INSERT INTO tasks VALUES(731,'Document steps to implement eco-friendly routines for a month',100);
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, username TEXT NOT NULL UNIQUE, hash TEXT NOT NULL);
INSERT INTO users VALUES(4,'Jessina','scrypt:32768:8:1$Qit1T04xteFocmcp$7322848eaa3d3cdbda1527af36ea1393b8d196637284f35c26353be220c2f561a316ba30c06df944c328bc8a95303c53b14b34b41f68c36e29d13da333f0071d');
PRAGMA writable_schema=ON;
CREATE TABLE IF NOT EXISTS sqlite_sequence(name,seq);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('quotes',100);
INSERT INTO sqlite_sequence VALUES('tasks',731);
INSERT INTO sqlite_sequence VALUES('users',4);
PRAGMA writable_schema=OFF;
COMMIT;
